### ISSUE TITLE
Raw data values check and how do I convert the them to uV?

### ISSUE THREAD

**Issue by seashrimp** [openyou/emokit#102]
Hi,

I managed to compile the Emokit C library under Windows (Win 7, 32bit). I took the “contacts.c” example and changed it to print the contact quality and the actual raw data values from each sensor. 

The code inside the loop that prints the values now looks like this:

```
c = emokit_get_next_frame(d);
fprintf(stdout,"\n\nContact quality:\nF3  %4d\nFC6 %4d\nP7  %4d\nT8  %4d\nF7  %4d\nF8  %4d\nT7  %4d\nP8  %4d\nAF4 %4d\nF4  %4d\nAF3 %4d\nO2  %4d\nO1  %4d\nFC5 %4d",c.cq.F3, c.cq.FC6, c.cq.P7, c.cq.T8,c.cq.F7, c.cq.F8, c.cq.T7, c.cq.P8, c.cq.AF4, c.cq.F4, c.cq.AF3, c.cq.O2, c.cq.O1, c.cq.FC5);
fprintf(stdout,"\n\nData:\nF3  %4d\nFC6 %4d\nP7  %4d\nT8  %4d\nF7  %4d\nF8  %4d\nT7  %4d\nP8  %4d\nAF4 %4d\nF4  %4d\nAF3 %4d\nO2  %4d\nO1  %4d\nFC5 %4d",c.F3, c.FC6, c.P7, c.T8,c.F7, c.F8, c.T7, c.P8, c.AF4, c.F4, c.AF3, c.O2, c.O1, c.FC5);
fflush(stdout);
```

The contact quality information seems to be ok – I have checked against the control panel, and the values seem to be very high when the particular contact quality is good and close to 0 when the contact quality is low. 

What I’m very unsure about are the values of the raw data. In another thread (https://github.com/openyou/emokit/issues/75) I found that they should be between -8192 and 8192, but that is not true in my case.

My question is: Are the raw data values I’m getting correct? If not, what could it be that I’m doing wrong? (Are at least the contact quality data ok?) In case the data are correct, how do I convert them to uV?

Here is an example of the output I get (with the device on my head):

```
Contact quality:
F3  6768
FC6 7056
P7  7488
T8  7632
F7   632
F8  5472
T7   776
P8  5912
AF4 2736
F4    24
AF3   16
O2  4592
O1     8
FC5 7776

Data:
F3  9001
FC6 8641
P7  9076
T8  8122
F7  8550
F8  7665
T7  8309
P8  8427
AF4 8641
F4  8588
AF3 6868
O2  7873
O1  8482
FC5 8723
```

**Comment by chochim** [comment]
Please pardon my ignorance, so suppose the value corresponding to F4 is x, we need to use the following to get the correct voltage (V)?
`V = (x-8192)*0.51`

Ist this correct or am I missing anything?

**Comment by bschumacher** [comment]
Perhaps, what do the values look like when you do that?

**Comment by bschumacher** [comment]
Thanks to some recent data we know that the values should look like floating point values that hover around 4k.

4099.4873046875,,4100.5126953125,,4114.8715820313,,4078.9743652344,,4130.7690429688,,4127.1791992188,,4114.8715820313,,4135.8974609375

**Comment by chochim** [comment]
Emokit is already doing this: https://github.com/openyou/emokit/blob/master/python/emokit/packet.py#L55 
We need to just multiply it by 0.51 microvolt (assuming 14-bit) to get the real value. I get the values as shown above if I set _is_research_ flag as True. The only problem that I am encountering is that some of the raw readings are around greater than 800. In such a scenario, the actual voltage comes out to be 408 microvolts. But EEG readings are in the range of 0 to 200 microvolts. So how come these readings surpass 200 microvolts?

**Comment by bschumacher** [comment]
We're doing it wrong, in short.

**Comment by bschumacher** [comment]
I'll play with my headset for a bit to see if I can correct that piece of it.

**Comment by warrenarea** [comment]
Bill, but note that the long floating point numbers that we seen, are from the Epoc+ in 256hz - 16bit mode.

Which would make sense, because... the Epoc+ is supposed to have a more detailed resolution, hence
more precision, which i believe is what the floating point numbers are for.

So the regular Epoc mode, should just be an integer.

You were right as stated that the Epoc measures in .51 microvolts.

However, the Epoc+ actually measures by .13 microvolts, which is where they are getting
the increased sensitivity.

There is some confusion in the specs on the website... they keep reporting it .31uv (microvolts)
but its actually .13uv

**Comment by warrenarea** [comment]
I'm not certain whether it matters what range of numbers it hovers around either.
As we've seen, it can be -8000 to +8000 

I think it has something to do with the reference sensors, and measuring the impedance.

So if your reference sensors are kind of wonky, I think it will likely reflect a completely
different range. 

Though I think a good working headset in normal operation, it likely does fall into the 4k range,
but shouldn't be used as a rule of thumb.

**Comment by bschumacher** [comment]
struct.unpack doesn't work in any combination of bits, the best you could hope for with that is ushorts. Multiplying by 0.51 would get the output near 4k, like we are seeing with the data. But I don't known how accurate the resolution is going to be.
