### ISSUE TITLE
Readme - dependencies

### ISSUE THREAD

**Issue by warrenarea** [openyou/emokit#123]
When I first started out, I remember having a lot of issues setting up
the dependencies. 

Particularly getting the right version of each. 

As this project has aged, so has the compiler + dependencies
python, greenlet, gevent, hidapi, etc.

I recommend placing the versions of each for clarification. 

I don't have linux set up at the moment, so I can't verify what
versions work for that, but I can verify that these versions worked
for Windows 7: 

`
    pywinusb 0.2.9  - https://pypi.python.org/packages/source/p/pywinusb/pywinusb-0.2.9.zip
    pycrypto 2.6 - http://www.voidspace.org.uk/downloads/pycrypto26/pycrypto-2.6.win32-py2.7.exe
    gevent 1.0.1 - www.lfd.uci.edu/~gohlke/pythonlibs/#gevent -> gevent‑1.0.1.win32‑py2.7.exe
    greenlet 0.4.2 - https://pypi.python.org/packages/2.7/g/greenlet/greenlet-0.4.2.win32-py2.7.exe#md5=0ea8f5a14f8554919e1a136bc042d76c
    Pygame(optional) 1.9.1 - http://pygame.org/ftp/pygame-1.9.1.win32-py2.7.msi
    Ctypes(optional)  gccxml 0.9.0 - http://downloads.sourceforge.net/project/ctypes/gccxml/2008-08-12/gccxml-0.9.0-win32-x86.exe

`
This will solve issues of people installing the latest versions of each to find they don't work.

**Comment by bschumacher** [comment]
Might be a good idea to move this to a wiki page or a file. I'm pretty sure the latest versions still work though.

**Comment by bschumacher** [comment]
These should be installed using pip install emokit or python setup.py install now. With the exception of pygame. requirements.txt now specifies the versions I use.
