### ISSUE TITLE
EEG option needed?

### ISSUE THREAD

**Issue by JanBam** [openyou/emokit#143]
This is rather a question than an issue, but I've found no answer in the FAQ.

When buying an Epoc there's an EEG option ($300). The store claims, that this option includes a different firmware for getting raw EEG data.

Do I need this option for using emokit?

**Comment by Razorblade2k** [comment]
I'm new here and I don't know the actual answer, but after having paid +$300 for the "raw EEG data" option, it seems to me that emokit can read raw data even without that option.

Emotiv says that the difference is in the firmware. jamesbeedy said in another thread that the difference is just the SDK software. I'm confused.

**Comment by llSourcell** [comment]
im curious of this as well. Anyone have an answer? @jamesbeedy

**Comment by nikhiljay** [comment]
Check this out: https://github.com/openyou/emokit/issues/139

**Comment by bschumacher** [comment]
Raw data is available using emokit.
