### ISSUE TITLE
Not running on Mac 10.10.4, Kernel 14.4.0

### ISSUE THREAD

**Issue by faturita** [openyou/emokit#149]
It is not running properly on this OS, it pops "Segmentation Fault: 11" on the 

```python
 hidraw.read(34)
```

It seems that you need to Open the hidraw device first providing the correct VendorID and ProductID.  It worked by adding that line to *Emotiv.py* code (line 512).

Let me know if you want me to push that.

Thanks btw, amazing work!

**Comment by bschumacher** [comment]
There was some pretty bad handling of detection and opening devices, this has been fixed in the latest pull request #154. 

Though the hidapi and pyhidapi are used now.

**Comment by bschumacher** [comment]
Closing open a new issue if latest version does not fix, unless one already exists.
