### ISSUE TITLE
Version should be increased in emokit.py after 'clean up'

### ISSUE THREAD

**Issue by fnielsen** [openyou/emokit#150]
`__version__ = "0.0.1"` in https://github.com/openyou/emokit/blob/master/python/emokit/__init__.py should be increased since https://github.com/openyou/emokit/commit/a4524a6309dbbe68757d3a83d52bf4b728be91ad changed names.

**Comment by bschumacher** [comment]
I've updated the version number in my latest pull request, thanks.
