### ISSUE TITLE
Battery level is not showing correct value in python version

### ISSUE THREAD

**Issue by fnielsen** [openyou/emokit#151]
Battery level is not showing correct value in python version. Here is an example:

    import gevent
    from emokit import emotiv
    
    headset = emotiv.Emotiv(display_output=False)
    gevent.spawn(headset.setup)
    gevent.sleep(0)
    
    try:
        while True:
            packet = headset.dequeue()
            line = "%d%%" % (packet.battery,)
            # print(line)
            gevent.sleep(0)
    except KeyboardInterrupt:
         headset.close()
    finally:
        headset.close()

I get, e.g.,:

    99%
    99%
    99%
    247%
    99%
    99%
    99%

**Comment by nathanielatom** [comment]
I always get 0% for battery life, despite the printed output from the Emotiv `print_console` method showing correctly.
