### ISSUE TITLE
Help?

### ISSUE THREAD

**Issue by nikhiljay** [openyou/emokit#159]
This is not really an issue, but I need help on how to use emokit. Right now I have a Emotiv EPOC and I need to extract raw data values for my project. Can someone teach me how to use emokit? I have a MacBook Pro by the way :)

**Comment by sat-turn** [comment]
in the exact same situation at the moment, was given an epoc headset without the research sdk, any help would be great!

**Comment by nikhiljay** [comment]
Oooh thanks! I will definitely try that.
