### ISSUE TITLE
Issue with running emotiv.py

### ISSUE THREAD

**Issue by sat-turn** [openyou/emokit#161]
Hi, ive installed all of the required libraries and depencicies successfully. however i am unsure on how to basically run the python library.

ive run emotiv.py and here is the result, any sort of guidance would be great:D

sanchir@ubuntu:~/Downloads/emokit-master/python/build/lib.linux-x86_64-2.7/emokit$ python emotiv.py build
Linux detected.
Traceback (most recent call last):
  File "emotiv.py", line 635, in <module>
    a.setup()
  File "emotiv.py", line 402, in setup
    self.setup_posix()
  File "emotiv.py", line 470, in setup_posix
    serial, hidraw_filename = get_linux_setup()
  File "emotiv.py", line 215, in get_linux_setup
    real_path = check_output(["realpath", "/sys/class/hidraw/" + filename])
  File "/usr/lib/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by nikhiljay** [comment]
I have the same problem. Thanks for asking.

**Comment by nikhiljay** [comment]
I am getting this error:
nikhils-mbp:emokit Nikhil$ python emotiv.py
Traceback (most recent call last):
  File "emotiv.py", line 9, in <module>
    import hid
ImportError: No module named hid

**Comment by sat-turn** [comment]
@nikhiljay have you installed hidapi yet?

**Comment by nikhiljay** [comment]
Ok I am getting your exact error. Have you resolve it yet?

**Comment by sat-turn** [comment]
@nikhiljay havnt had any luck since the post, please let me know if you do resolve it. ill keep at it as well

**Comment by nikhiljay** [comment]
Oh I think I got something. I changed my directory from the emokit directory to the python directory and then tried to run "python example.py". This was after I inputted the serial number and configured emotiv.py in the emokit directory. After running example.py, I got this output:

<img width="293" alt="2016-03-30 at 12 01 25 pm" src="https://cloud.githubusercontent.com/assets/4722743/14154020/464131c2-f66f-11e5-9a1b-f92c40e8d524.png">

Later today, I am going to connect the emotiv and test it out to see if I get any actual values :)

**Comment by nikhiljay** [comment]
GOT IT WORKING! :smiley: 

<img width="334" alt="2016-03-30 at 10 18 21 pm" src="https://cloud.githubusercontent.com/assets/4722743/14168130/03da5e4c-f6d5-11e5-86ee-d55871b035b1.png">

I have the instructions in the readme of my repo: https://github.com/nikhiljay/brainwaves

**Comment by sat-turn** [comment]
@nikhiljay that brillaint!, thanks very much for the guide. i was going through it and in step 5 to 6 
5) A hidtest file should be created in the same directory. Open the hidtest to run it.

6) The output should be a list of devices that are connected to the computer. Look at the Emotiv device information and copy the Serial Number.

i cant seem to compile the cpp file, initially it said the an hidapi.h was missing but i pasted in from another directory then a series of errors came up.  how did you get past this?

![screenshot from 2016-03-31 14 35 11](https://cloud.githubusercontent.com/assets/18108305/14191650/de41895c-f74d-11e5-9951-abc808022465.png)

**Comment by bschumacher** [comment]
Looks like your kernel doesn't support hidraw, you might try pulling the latest version.

**Comment by bschumacher** [comment]
Which version of ubuntu are you running? Did you compile a custom kernel?

**Comment by bschumacher** [comment]
If you need further assistance please open a new issue, after re-reading this it appears your problem is related to the compilation and installation of the hidapi library.
