### ISSUE TITLE
Split C and Python Libraries into different repos?

### ISSUE THREAD

**Issue by qdot** [openyou/emokit#168]
It looks like the python library in this repo sees far more updates and attention than the C library. Should we split the C code into its own repo? That may relieve some of the bug/review pressure here, as well as letting us version the python code apart from the C. I usually just do one repo per language with my projects these days anyways.

**Comment by bschumacher** [comment]
Sounds good to me.

**Comment by qdot** [comment]
'k. I'll take care of the cleanup and split, will put in a pull request once it's done.

**Comment by warrenarea** [comment]
i think splitting it is a good idea.

**Comment by warrenarea** [comment]
qdot (kyle) 
sorry to bother you... but I noticed Bill Schumacher has deleted his account.
any ideas whats going on there... or who has taken the reigns for emokit?

**Comment by qdot** [comment]
@warrenarea Thanks for getting in touch.

Uh. Wow. That's odd. Sure enough, account seems dead, and no commits since April. Moving discussion to #279.
