### ISSUE TITLE
Python 3 Support

### ISSUE THREAD

**Issue by qdot** [openyou/emokit#176]
Emokit is currently python 2. Would it be worth considering python 3 support?

**Comment by qdot** [comment]
(I have no opinion on this matter, just making sure the question didn't get lost in #175)

**Comment by bschumacher** [comment]
Yeah I had planned on it anyways.

**Comment by jonrei** [comment]
I have a working port in python3, but I have also removed the old Crypto and replaced it with cryptography, and removed gevents in favor of just having a generator which makes it kind of a large change. Most likely I have missed some use cases/functionality, I have only tested it on my current setup (mac with epoc+).
I think the changes are too large to easily accomodate as a pull request, and py2 support would be lost too. The code is available [here](https://github.com/butternutdog/emoren/blob/master/emoren.py) if anyone is interested in somehow integrating my changes or do anything useful with it.

**Comment by mdtdev** [comment]
@jonrei ...And you have confirmed that it is working with EPOC+ -- recent posts here are suggesting some potential problems with that; and I have been unable to confirm the data stream is a proper signal on mine. You are satisfied you are pulling good data? (If you are, you are awesome and saving my life!) :smile:

**Comment by jonrei** [comment]
@mdtdev Yes it is EEG data from an EPOC+ bought 3 months ago, if you want to try it out there are some rudimentary instructions [here](https://github.com/butternutdog/emoren).

**Comment by warrenarea** [comment]
good work. is it functional? or are you having problems with it?

**Comment by qdot** [comment]
Hmm. I think I'd be ok with py2.7 compatibility, which I think this would still hit? Not like you're using async/await, and cryptography is 2.6+. Most libraries I use these days only support python 2.7+ and 3+ anyways.

**Comment by jonrei** [comment]
Made a small fix to make it compatible with 2.7+, seems fully functional.

**Comment by qdot** [comment]
Yeah, really need to get CI up and running to make sure we stay working across versions, but no reason to block on that right now, we've been without it for years as is heh. Wanna go ahead and PR it?

**Comment by jonrei** [comment]
Created a [PR](https://github.com/openyou/emokit/pull/180)
I guess the examples should be rewritten too. As is, I think it causes a bit too much breakage.

**Comment by qdot** [comment]
Well, the main reason I wanted at PR is to remind me and others that the code is there at least. Otherwise it kinda gets lost in bug comments.
