### ISSUE TITLE
How to install on linux?

### ISSUE THREAD

**Issue by matthew-groth** [openyou/emokit#179]
It says that "hidapi will still need to be installed manually on Linux and OS X.".

Where are the instructions for how to do this?

**Comment by bschumacher** [comment]
http://www.signal11.us/oss/hidapi/

Download

HIDAPI can be downloaded from GitHub. A zip file is available from the Download Page. To get the latest trunk revision (if you have git installed, run the following:
   git clone git://github.com/signal11/hidapi.git
Build Instructions

Windows: 
Build the .sln file in the windows/ directory using Visual Studio. 

Linux: 
Change to the linux/ directory and run make. 

Mac OS X: 
Change to the mac/ directory and run make.
