### ISSUE TITLE
Export Data written to CSV as actual sensor values

### ISSUE THREAD

**Issue by jemSquashness** [openyou/emokit#183]
What data is written to the CSV and in what order? 
Is the bit stream converted to decimal and plugged into the CSV file, if so, do we need to convert to binary and concatenate different bytes? 
I've compared data from the Emokit library and the actual SDK research edition and there only seems to be minor correlations without editing the data from Emokit. 
Please can anyone who's managed to use this for actual EEG readings give me a hand. 
Thanks!

**Comment by bschumacher** [comment]
It is the data that constructs each individual packet in the order received, separated by commas.

It can be written before decryption or after, if the latter a serial number is required when using the reader to decrypt the data.

**Comment by jemSquashness** [comment]
Is this data processed at all? Has it had the dc offset removed?

**Comment by bschumacher** [comment]
The data is unprocessed.

**Comment by jemSquashness** [comment]
Is it in decimal? Or some other number system?

**Comment by bschumacher** [comment]
I would recommend looking at the source for the EmotivPacket class to see how the actual values are obtained and correlated to specific sensor levels.

You can't use the data without some processing.

**Comment by jemSquashness** [comment]
I do understand that, the DSP isn't the problem. I'm just confused as to why the Emokit values don't correlate to the actual Sdk research values. It should be a similar process to write them to a csv file as the csv is generated from the .edf which is just a print out of packet data, right? By no correlation i mean that they're not even in similar number ranges.

**Comment by bschumacher** [comment]
I've never seen the research data output, I assume it is a file that has sensor values separated by commas for each packet separated by commas. 

This is the raw data stream from the dongle and was meant more for debugging and further development of the library with new headsets than to be used as a representation of actual signal values without being processed as an emokit packet.

**Comment by jemSquashness** [comment]
Ok great, thank you for your time. 
Will try and work with the decrypted stream directly and see if i can get actual sensor values. Will post any progress.

**Comment by bschumacher** [comment]
That all being said I understand what you are trying to accomplish and have added it to my todo list.

**Comment by bschumacher** [comment]
I updated my fork with this functionality.

It may or may not work correctly on Windows. Linux or OS X should be fine though. 

Still struggling to get my Windows VM to recognize my dongle.

**Comment by jemSquashness** [comment]
Ok great, thanks again. 
Will test it out tomorrow.
