### ISSUE TITLE
How can I know the name of the channels

### ISSUE THREAD

**Issue by yenylm14** [openyou/emokit#186]
Hi.
How can I know the name of channels when I import the CSV file to Matlab (with uiopen function)?, is because Matlab just say that have 33 vector but I don't know what is each one. I'm new using Emokit.

Thanks

**Comment by bschumacher** [comment]
The current CSV file does not contain the data you are looking for, my latest PR includes exporting signal levels in a readable format, might not work on Windows though.

**Comment by bschumacher** [comment]
The example_export will now default the channel names as the first row in the file.
