### ISSUE TITLE
example_export does not provide a valid windows file name

### ISSUE THREAD

**Issue by ppasler** [openyou/emokit#187]
Hi guys,

starting the example_export.py leads to an error, as windows filenames are not allowed to contain ":" (emotiv_dump_2016-09-21 11:55:01.658000.csv).

In emotiv.py:483 you could use `time.strftime("%Y-%m-%d-%H-%M", time.gmtime())` instead of `str(datetime.now())`

Thanks in advance,
paul

**Comment by bschumacher** [comment]
I'll work on testing my PR on a Windows system later today and include this.
