### ISSUE TITLE
Sampling rate too low

### ISSUE THREAD

**Issue by pranaydeep-af** [openyou/emokit#192]
Using the device with the EPOC Headset, All packets are processed and none are lost, the device sampling rate is still too low. Close to around 50-55Hz. Could there be a configuration mistake? Or is the device faulty?

**Comment by bschumacher** [comment]
Are you running the example or something else?

**Comment by pranaydeep-af** [comment]
I have tried running the various codes, one of them was the example. No luck with any of them. I am on Ubuntu Gnome 16.04 and using the hidraw bindings.
Thanks for the help

**Comment by bschumacher** [comment]
If you could use the code that is mentioned above and tell me what it says the sampling rate is.

I can confirm on my system that it should be 128.

**Comment by bschumacher** [comment]
Did you happen to see if this gave you a value other than 127-128 after running for a few seconds?

**Comment by bschumacher** [comment]
If you're still seeing abnormal performance please open another issue.
