### ISSUE TITLE
Python2 'Queue' instead of 'queue'

### ISSUE THREAD

**Issue by Morgan243** [openyou/emokit#208]
The queue module in is capitalized for Python2, but lower case for Python3, [see docs](https://docs.python.org/2/library/queue.html). I've replaced imports in my own code with something like the following:

```
try:
    from queue import Queue
except:
    from Queue import Queue
```

It seems like this project is aiming to support both Python 2 & 3, so this should be fixed unless I'm mistaken. I can push a commit to fix if need be.

**Comment by bschumacher** [comment]
That would be great.

**Comment by bschumacher** [comment]
Thanks!
