### ISSUE TITLE
Render example needs updating to support altered packet structure

### ISSUE THREAD

**Issue by Morgan243** [openyou/emokit#209]
'render.py' looks like it needs to be updated to support changes to the packet object structure - references like packet.gyro_x and packet.old_model appear to be invalid and cause run-time errors. Perhaps the devs are waiting until further changes to the underlying library are complete?

**Comment by bschumacher** [comment]
Just something I haven't gotten to yet, as the core library is intended as a means to extract the data from the headset.

Feel free to submit a PR.
