### ISSUE TITLE
Remove CSV library

### ISSUE THREAD

**Issue by bschumacher** [openyou/emokit#247]
This CSV library was indeed a mistake, it needs to go.

Detecting the end of the file is near impossible, or I'm not looking in the right place, it throws stop iteration unexpectedly...

It's pretty much garbage IMO.

**Comment by minifiredragon** [comment]
Does this help?
Basically you only know you've run out after you've run out. So you could wrap the reader iterator, e.g. as follows:

def isLast(itr):
  old = itr.next()
  for new in itr:
    yield False, old
    old = new
  yield True, old

**Comment by ghost** [comment]
It's been removed.
