### ISSUE TITLE
How could I get sensors value array

### ISSUE THREAD

**Issue by shihray** [openyou/emokit#261]
hi everyone
i'm try to use headset.dequeue() to get values
gust like packet.sensors['AF3']['value']
but this just can get one value
how to get sensors value to array

**Comment by ghost** [comment]
packet.sensors is a dictionary of all the values.

**Comment by shihray** [comment]
@bschumacher thanks for your answer
but I want to get an array its length is 128 in one second
how could I make that come true

**Comment by ghost** [comment]
You would append the packet.sensors to a list, unless you're using numpy arrays.

When the list length is equal to 128 append that list to another list assuming you want to keep it around or perform your processing or whatever.

**Comment by shihray** [comment]
@bschumacher thanks a lot 
I got it
