### ISSUE TITLE
headset.dequeue() is None

### ISSUE THREAD

**Issue by shihray** [openyou/emokit#262]
Hello, I'm trying to use a thread to do my work before start load packet using headset.dequeue()
then I can't get the packet result (it will become None) 
so is that can't use thread with emokit together?

**Comment by ghost** [comment]
Your thread is executing before data is returned from the headset.

You need to add a check:

    if packet is not None:
        print(packet)

**Comment by shihray** [comment]
@bschumacher I doing this before my work
my question is the data return from headset was all None
I can't get another result
