### ISSUE TITLE
Large values

### ISSUE THREAD

**Issue by ShaneHudson** [openyou/emokit#272]
I'm new to emokit, and am wanting to use the raw data from an EPOC+. It doesn't need to be 100% accurate, but I want it to be useable for detecting differences to show readings while listening to different types of music.

As you can see from the screenshot, the values are coming back much larger than expected. Am I interpreting them wrong? Or is there an issue?

<img width="503" alt="screenshot 2017-09-03 16 25 42" src="https://user-images.githubusercontent.com/487005/30004323-e6371980-90c4-11e7-8e4d-c198a70b9885.png">

**Comment by Vsevalot** [comment]
If I understood datasheet right, epoc+ has resolution 14 bit, with LSB = 0.51μV, so to get voltage value you should subtract 4096 from your data and multiply result to 0.51μV

Epoc + datasheet: https://www.emotiv.com/files/Emotiv-EPOC-Product-Sheet-2014.pdf

**Comment by ShaneHudson** [comment]
Ah brilliant thank you!
