### ISSUE TITLE
Mapping Facial Expressions to Raspberry Pi

### ISSUE THREAD

**Issue by Shahad56** [openyou/emokit#276]
Hi...
I'm working on a project that converts facial expressions taken from Emotiv insight headset and to movement. I don't know what code to start with! I installed Rasbian OS on my raspberry and I'm all aware of Python code. Please help, This is a serious :(

**Comment by warrenarea** [comment]
you'll probably have an easier experience with the 
emotiv - community sdk (on github) 
and start with the python logger in /examples_extra_prime/ , 
i think it can detects facial expressions.
