### ISSUE TITLE
Hacking it: Choosing the right USB port

### ISSUE THREAD

**Issue by nahawtho** [openyou/emokit#287]
Windows 10
Microsoft VS 2015 (V 14)
successfully installed all dependencies
running py -2.7 -m pytest tests/ inside of developer edition VS 2015 command prompt.

Fixed errors by changing EmotivPacket to Emotiv, and sensor_bits to sensors_16_bits dictionary from emotiv/emotiv.py.
Passing 5/6 tests. The remaining test, which I don't pass is in line 49 of test_packet.py: assert packet.battery == None. I comment this line out, and now am passing the tests.

My Problem Is:
Where I SHOULD SEE the electrode numbers, the battery, the contact quality, etc, in that little chart
I am seeing hidapi list the available usb ports, and usb audio ports, instead of the epoc+ (I have epoc+ 2015).

Any way to narrow in on the port/ has anyone had this problem before? I know tests\ want no epoc+ plugged in w the sample data, but I have tried connecting as well, with no success. I have records of almost everything I've done if you need more information. I would like emokit to thrive ! ahah!

**Comment by warrenarea** [comment]
emokit is currently broken, you should
try using https://github.com/CymatiCorp/CyKITv2 
instead, until it can be fixed.
