### ISSUE TITLE
Help with integrating emokit with another project

### ISSUE THREAD

**Issue by Happy0** [openyou/emokit#58]
I wish to make a emokit driver for this project: https://github.com/SmartphoneBrainScanner/smartphonebrainscanner2-core/tree/master/src/hardware . I understand what interfaces I need to implement in the above project and how I need to use the emokit library, but i'm a bit lost in terms of the building side of things with the emokit library... I notice they have hidapi covered in here  
 [https://github.com/SmartphoneBrainScanner/smartphonebrainscanner2-core/blob/master/src/sbs2.pri], and i could refer to that header file in emokit.c/h, but I'm not sure what I need to do about mcrypt... can anybody give me a much appreciated hand?

I'm only accustomed to using standard libraries with C and writing uncomplicated Makefiles... I wish I had more experience! Sorry if this question is ill posed...

Closed: I seem to have a better idea of how libraries work in C now... Found libemokit.a. Sorry for posing this question at all!

**Comment by joshuamanns** [comment]
@Happy0 would you mind sharing what you did to solve this? I have `libemokit.a` in my /usr/local/lib directory but still no dice. Did you modify the core project to include it?

**Comment by Happy0** [comment]
@joshuamanns I really wish I could help, but I've forgotten almost everything about the project I did with this 4 years ago :(. I can't even remember what the problem was here...

Best of luck.

**Comment by Happy0** [comment]
@joshuamanns it was really annoying me that I'd left you in this situation: https://xkcd.com/979/ , so I'm going to try to help you.

I managed to look hard and dig up my old project code. It looks like I might have added some stuff in the smartphone brain scanner project's 'hardware' folder to work with emokit or something? I'll have a better look later. For now, here is the 'hardware' folder I had in my smartphonebrainscanner2-core folder, in case that helps: https://www.dropbox.com/s/i6lcadxlob70vwh/hardware.zip?dl=0
