### ISSUE TITLE
New Headset has different vendor and product ids

### ISSUE THREAD

**Issue by sanedragon** [openyou/emokit#63]
```
$ lsusb
<snip>
Bus 005 Device 008: ID 1234:ed02 Unknown Emotiv EPOC Developer Headset Wireless Dongle
```

Changing the values of EMOKIT_VID and EMOKID_PID in emokit/emokit.h lets me get a little farther with the contact example, although hid_open_path() is still failing.

**Comment by bschumacher** [comment]
Python version should work as well. Closing.
