### ISSUE TITLE
Building on Windows using Visual Studio 2010

### ISSUE THREAD

**Issue by phuntyme** [openyou/emokit#91]
I'm running into issues trying to build on Windows 7 x64 using VS 2010.
I'm pretty far along - as much as I can tell - but I'm beginning to think I'm doing something wrong just because I'm having to make a number of edits to the source. Perhaps this can serve as a guide for someone else who travels down the same road I've traveled.

I already have the hidapi and mcrypt libraries in the include path for emokit and have used CMake-gui to generate the VS solution files.

When I first tried to compile, errors were thrown due to the strict C compiler used in VS. 
That was an easy fix; I just declared all of the variables at the beginning of each function.

Once that was situated, I was receiving errors about a few of the header file references in emokitd.c:
- unistd.h
- syslog.h
- pthread.h
- sys/resource.h

After a decent amount of hunting down the header files, a few more were found to be necessary:
- getopt.h
- sched.h
- sys/cdefs.h

I am now receiving errors about the existence of a few data types, which are not part of standard C, and a number of other structs, functions and constants. Some of them were included in the header files I've found, but here is the list of those still missing. Note that all of these references are in thr_signal_handler, daemon_running, and daemonize functions in emokitd.c.

data type:
- sigset_t

structs:
- flock
- sigaction

functions:
- sigwait
- fcntl
- fork
- setsid
- sigemptyset
- chdir

constants:
- SIGPIPE
- LOCKMODE  (S_IRUSR, S_IWUSR, S_IRGRP, S_IROTH)
- F_WRLCK
- F_SETLK
- RLIMIT_NOFILE
- SIGHUP

I found a definition of sigset_t, so I added this just after the include statements:
# define _NSIG 64
# define _NSIG_BPW 32
# define _NSIG_WORDS (_NSIG / _NSIG_BPW)

typedef unsigned long old_sigset_t; /\* at least 32 bits */ 

typedef struct { 
unsigned long sig[_NSIG_WORDS]; 
} sigset_t; 

And this is where I started thinking that I could be doing something wrong.

I can continue going through all of the remaining struct and function definitions and find all of the constants, but is this really the right way to do this? Am I on the right path?

Thanks to everyone for their work on this great project - this is the reason I bought the EPOC.

**Comment by vivek306** [comment]
hi, long time since u played around with this.. I finally managed to do the same with cygwin but :) did u manage to these to the vs?
